name: Check Standoff 2
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
permissions:
  actions: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: python check.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CURRENT_VERSION: "0.39.2"
      - if: steps.check.outputs.updated == 'true'
        run: gh workflow disable "Check Standoff 2"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
